# Generated by Django 5.2.5 on 2026-09-01 15:21

import django.db.models.functions.comparison
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_stories", "0003_alter_post_options_alter_postcontent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "get_latest_by": "date_published",
                "ordering": (
                    models.OrderBy(
                        models.Case(
                            models.When(
                                date_featured__lte=django.db.models.functions.datetime.Now(),
                                then=models.F("date_featured"),
                            ),
                            default=None,
                            output_field=models.DateTimeField(),
                        ),
                        descending=True,
                        nulls_last=True,
                    ),
                    models.OrderBy(
                        django.db.models.functions.comparison.Coalesce("date_published", "date_created"),
                        descending=True,
                    ),
                    models.OrderBy(models.F("date_created"), descending=True),
                ),
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AlterModelOptions(
            name="postcontent",
            options={
                "get_latest_by": "post",
                "ordering": (
                    models.OrderBy(
                        models.Case(
                            models.When(
                                post__date_featured__lte=django.db.models.functions.datetime.Now(),
                                then=models.F("post__date_featured"),
                            ),
                            default=None,
                            output_field=models.DateTimeField(),
                        ),
                        descending=True,
                        nulls_last=True,
                    ),
                    models.OrderBy(
                        django.db.models.functions.comparison.Coalesce("post__date_published", "post__date_created"),
                        descending=True,
                    ),
                    models.OrderBy(models.F("post__date_created"), descending=True),
                ),
                "verbose_name": "post content",
                "verbose_name_plural": "post contents",
            },
        ),
        migrations.AddField(
            model_name="latestpostsplugin",
            name="featured_first",
            field=models.BooleanField(
                default=True,
                help_text="List featured posts before recent ones. Careful: if you feature as many posts as this plugin shows, no recent post will be displayed any more.",
                verbose_name="featured posts first",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_featured",
            field=models.DateTimeField(
                blank=True,
                help_text="Featured posts are listed before other posts, most recently featured first. Leave empty for regular order by date, or set a future date to feature the post from that date on.",
                null=True,
                verbose_name="featured date",
            ),
        ),
    ]
