# Generated by Django 6.0.4 on 2026-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_stories', '0003_alter_post_options_alter_postcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesconfig',
            name='template_style',
            field=models.CharField(blank=True, default='', help_text='Select the template style for this blog instance.', max_length=200, verbose_name='Template Style'),
        ),
        migrations.AlterField(
            model_name='storiesconfig',
            name='url_patterns',
            field=models.CharField(max_length=12, verbose_name='Permalink structure'),
        ),
    ]
