name: migration test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate-project:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        requirements: [
          'dj52_cms41.txt',
        ]
        python-version: ['3.13']
        os: [
          ubuntu-latest,
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m venv .venv
        source ./.venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements/${{ matrix.requirements }}
    - name: Test migration from djangocms Blog to djangocms Stories
      run: |
        source ./.venv/bin/activate
        python tests/test_migrations/run.py test_migrations --phase1
        python tests/test_migrations/run.py test_migrations --phase2
